[features]
seeds = false
skip-lint = false

[programs.localnet]
soldrive = "E4nVBaHnofwEpP8nnN76vrMQJ6c1qVk6xpLMGz9ZXVjc"

[programs.devnet]
soldrive = "E4nVBaHnofwEpP8nnN76vrMQJ6c1qVk6xpLMGz9ZXVjc"

[programs.mainnet]
soldrive = "E4nVBaHnofwEpP8nnN76vrMQJ6c1qVk6xpLMGz9ZXVjc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
